syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";
import "domain/v1/vision/vision.proto";
import "domain/v1/location/location.proto";

option java_multiple_files = true;
option java_package = "br.com.v3.protocol.domain.events";
option java_outer_classname = "SystemEventProto";
option go_package = "github.com/v3-tecnologia/protocol-cloud/proto/gen/domain/v1/events;v1";
option optimize_for = CODE_SIZE;

package domain.events.v1;

enum PingType {
  option allow_alias = true;
  PING_TYPE_UNSPECIFIED = 0;
  PING_TYPE_ECONOMIC_MODE = 1; // Ping is successful
  PING_TYPE_TEST_MODE = 2; // Ping failed

  // For compatibility with JSON naming conventions
  ECONOMIC_MODE = 1;
  TEST_MODE = 2;
}

message UploadEvent {
  string name = 1 [(buf.validate.field).string.min_len = 1]; // e.g., "UPLOAD_EVENT"
  string source_id = 2 [(buf.validate.field).string.min_len = 1]; // e.g., "12345"
  repeated domain.vision.v1.FileAddress files = 3;
  domain.location.v1.Location location = 4;
}

message PingEvent {
  string name = 1 [(buf.validate.field).string.min_len = 1]; // e.g., "PING_EVENT"
  PingType type = 2;
  domain.location.v1.Location location = 3;
}

message RebootEvent {
  string name = 1 [(buf.validate.field).string.min_len = 1]; // e.g., "REBOOT_EVENT"
  string reason = 2; // Reason for reboot
  domain.location.v1.Location location = 3;
}

message System {
  string id = 1 [(buf.validate.field).string.min_len = 1];
  string event_name = 2 [(buf.validate.field).string.min_len = 1]; // e.g., "SYSTEM_EVENT"
  oneof event {
    UploadEvent upload = 3;
    RebootEvent reboot = 4;
    PingEvent ping = 5;
  }
  google.protobuf.Timestamp timestamp = 100 [(buf.validate.field).timestamp.lt_now = true];
}
