<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.2" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="protobuf-net.Grpc" Version="1.2.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>

    <ItemGroup>
      <Protobuf Include="Protos/**/*.proto" CompileOutputs="false" OutputDir="Generated" GrpcServices="None" AdditionalImportDirs="Protos" />
    </ItemGroup>

</Project>
